-- List table in tablespace
SELECT substr(A.TABNAME,1,25) as TABLE_NAME, substr(A.TABSCHEMA,1,25) as TABLE_SCHEMA, substr(B.TBSPACE,1,25) as TABLE_SPACE FROM SYSCAT.TABLES A INNER JOIN SYSCAT.TABLESPACES B ON A.TBSPACEID = B.TBSPACEID

-- Total table in tablespace
SELECT substr(B.TBSPACE,1,25), COUNT(*) AS TOTAL_TABLES FROM SYSCAT.TABLES A INNER JOIN SYSCAT.TABLESPACES B ON A.TBSPACEID = B.TBSPACEID WHERE A.TBSPACE LIKE 'DB%' GROUP BY B.TBSPACE;

-- List all table on database
SELECT TAB.TABSCHEMA AS TABSCHEMA, TAB.TABNAME AS TABNAME, TAB.CREATE_TIME, TAB.ALTER_TIME FROM SYSCAT.TABLES TAB WHERE TAB.TYPE = 'T' AND TAB.TABSCHEMA NOT LIKE 'SYS%' AND TAB.TABSCHEMA NOT IN ('DB2INST1','DB2ADMIN') ORDER BY TAB.TABSCHEMA, TAB.TABNAME

-- Total table in each table schema
SELECT TAB.TABSCHEMA AS TABSCHEMA, COUNT(*) AS TOTAL_TABLES FROM SYSCAT.TABLES TAB WHERE TAB.TABSCHEMA NOT IN ('DB2INST1','DB2ADMIN','DB2AC3') AND TAB.TABSCHEMA NOT LIKE 'SYS%' GROUP BY TAB.TABSCHEMA ORDER BY TAB.TABSCHEMA, TOTAL_TABLES

-- List all table size 
SELECT TAB.TABSCHEMA AS TABLE_SCHEMA, TAB.TABNAME AS TABLE_NAME, NPAGE AS TOTAL_PAGES, FPAGE AS FREE_PAGES, MPAGE AS ACTUAL_USED_PAGES FROM SYSCAT.TABLES TAB

-- List Application perform large table scan
SELECT APPLICATION_HANDLE, ROWS_READ_PER_ROWS_RETURNED FROM SYSIBMADM.MON_CONNECTION_SUMMARY

-- List longest queries being executed
SELECT ELAPSED_TIME_SEC, ACTIVITY_STATE, ACTIVITY_TYPE, APPLICATION_HANDLE FROM SYSIBMADM.MON_CURRENT_SQL ORDER BY ELAPSED_TIME_SEC DESC

-- Check page size
SELECT SUBSTR(TBSP_NAME,1,15) NAME, TBSP_TYPE TYPE,TBSP_AUTO_RESIZE_ENABLED AUTO_RESIZE, TBSP_NUM_CONTAINERS CONTAINERS, TBSP_TOTAL_PAGES TOTAL_PGS, TBSP_USED_PAGES USED_PGS, TBSP_FREE_PAGES FREE_PGS,TBSP_MAX_SIZE MAX_SZ, TBSP_PAGE_SIZE PG_SZ, (TBSP_USED_PAGES-TBSP_FREE_PAGES)/TBSP_NUM_CONTAINERS NPAGES, TBSP_CONTENT_TYPE FROM SYSIBMADM.TBSP_UTILIZATION
SELECT SUBSTR(TBSP_NAME,1,15) NAME, TBSP_TYPE TYPE, TBSP_