---
- name: Copy nessesary files to machine
  hosts: all
  become: no
  vars:
    username: resmonitor
    destination_folder: /home/{{ username }}
    script_folder: scripts/get_resource
  tasks:

    - name: Copy get_resources.sh to "{{ script_folder }}" folder
      ansible.builtin.copy:
        src: "./get_resource/get_resources.sh"
        dest: "{{ destination_folder }}/{{ script_folder }}"
        mode: '0755'

    - name: Copy settings.properties to "{{ script_folder }}" folder
      ansible.builtin.copy:
        src: "./get_resource/settings.properties"
        dest: "{{ destination_folder }}/{{ script_folder }}"
        mode: '0755'

    - name: Exit session
      ansible.builtin.meta: reset_connection