---
- name: Create user
  hosts: all
  become: no
  vars:
    new_username: resmonitor
    new_password_plain: "cx1@VNresmon"
  tasks:

    - name: Encrypt password
      ansible.builtin.set_fact:
        encrypted_password: "{{ new_password_plain | password_hash('sha512') }}"

    - name: Create user {{ new_username }}
      ansible.builtin.user:
        name: "{{ new_username }}"
        password: "{{ encrypted_password }}"
        shell: /bin/bash
        state: present
        generate_ssh_key: true
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
    
    - name: Exit session
      ansible.builtin.meta: reset_connection
