---
- name: Create folders 
  hosts: linux-first
  become: no
  vars:
    username: resmonitor
    destination_folder: "/home/resmonitor"
    script_folder: "scripts"
  tasks:

    - name: Create "{{ script_folder }}" folder
      ansible.builtin.file:
        path: "{{ destination_folder }}/{{ script_folder }}"
        state: directory  
        mode: '0755'

    - name: Create "get_resource" folder
      ansible.builtin.file:
        path: "{{ destination_folder }}/{{ script_folder }}/get_resource"
        state: directory  
        mode: '0755'

    - name: Create temp folder
      ansible.builtin.file:
        path: "{{ destination_folder }}/{{ script_folder }}/get_resource/temp"
        state: directory
        mode: '0755'
    
    - name: Exit session
      ansible.builtin.meta: reset_connection