---
- name: Create cronjob
  hosts: all
  become: no
  vars:
    username: resmonitor
    script_file: /home/{{ username }}/scripts/get_resource/get_resources.sh
  tasks:

    - name: Delete cron job
      ansible.builtin.cron:
        name: "##Get resource##"
        state: "absent"

    - name: Create cron job
      ansible.builtin.cron:
        name: "##Get resource##"
        minute: "*/5"
        job: /bin/bash {{ script_file }}

    - name: Exit session
      ansible.builtin.meta: reset_connection