- name: Create cron job for resource monitoring
  hosts: all
  become: no
  vars_files:
    - secrets.yml
  vars:
    ansible_user: "{{ admin_user }}"
    ansible_password: "{{ admin_password }}"
    ansible_ssh_host_key_checking: false
    username: resmonitor
    script_file: /home/{{ username }}/scripts/get_resource/get_resources.sh
  tasks:
    - name: Delete existed cron job
      ansible.builtin.cron:
        name: "##Get resource##"
        state: "absent"

    - name: Create cron job
      ansible.builtin.cron:
        name: "##Get resource##"
        minute: "*/5"
        job: /bin/bash {{ script_file }}

    - name: Exit session
      ansible.builtin.meta: reset_connection