- name: Create folder for resource monitoring
  hosts: all
  become: no
  vars_files:
    - secrets.yml
  vars:
    ansible_user: "{{ normal_user }}"
    ansible_password: "{{ user_password }}"
    ansible_ssh_host_key_checking: false
    username: "{{ normal_user }}"
    destination_folder: "/home/{{ username }}"
    script_folder: "scripts"
  tasks:
    - name: Create "{{ script_folder }}" folder
      ansible.builtin.file:
        path: "{{ destination_folder }}/{{ script_folder }}"
        state: directory  
        mode: '0755'

    - name: Create "get_resource" folder
      ansible.builtin.file:
        path: "{{ destination_folder }}/{{ script_folder }}/get_resource"
        state: directory  
        mode: '0755'

    - name: Create temp folder
      ansible.builtin.file:
        path: "{{ destination_folder }}/{{ script_folder }}/get_resource/temp"
        state: directory
        mode: '0755'
    
    - name: Exit session
      ansible.builtin.meta: reset_connection