---
- name: Create user
  hosts: linux
  become: yes
  vars:
    new_username: resmonitor
    new_password_plain: "cx1@VNresmon"
  tasks:

    - name: Create password
      ansible.builtin.set_fact:
        encrypted_password: "{{ new_password_plain | password_hash('sha512') }}"

    - name: Create user {{ new_username }}
      ansible.builtin.user:
        name: "{{ new_username }}"
        password: "{{ encrypted_password }}"
        shell: /bin/bash
        state: present
        create_home: yes
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
