all:
  linux-first:
      hosts:
        10.165.48.1:
        10.165.48.2:
        10.165.48.51:
        10.165.48.53:
  linux-second:
      hosts:
        10.165.49.1:
        10.165.49.2:
        10.165.68.1:
        10.165.68.2:
        10.165.68.51:
        10.165.68.52:
      vars:
        ansible_user: root
        ansible_password: redhat
        ansible_ssh_host_key_checking: false