---
- name: Create user
  hosts: all
  become: no
  vars:
    remove_username: sys_perf
  tasks:

    - name: Remove user {{ remove_username }}
      ansible.builtin.shell: |
        pkill -u {{ remove_username }} || true

    - name: Wait for processes to finish
      ansible.builtin.wait_for:
        timeout: 3
    
    - name: Remove user {{ remove_username }}
      ansible.builtin.user:
        name: "{{ remove_username }}"
        state: absent
        remove: true
      register: user_removal_result

    - name: Check if user removal was successful
      ansible.builtin.debug:
        msg: "User {{ remove_username }} removed successfully."
      when: user_removal_result is changed

    - name: Remove {{ remove_username }} home directory
      ansible.builtin.file:
        path: "/home/{{ remove_username }}"
        state: absent

    - name: Exit session
      ansible.builtin.meta: reset_connection