---
- name: Create user
  hosts: all
  become: no
  vars:
    username: resmonitor
  tasks:

    - name: Remove user {{ username }}
      ansible.builtin.shell: |
        pkill -u {{ username }} || true

    - name: Wait for processes to finish
      ansible.builtin.wait_for:
        timeout: 3
    
    - name: Remove user {{ username }}
      ansible.builtin.user:
        name: "{{ username }}"
        state: absent
        remove: true
      register: user_removal_result

    - name: Check if user removal was successful
      ansible.builtin.debug:
        msg: "User {{ username }} removed successfully."
      when: user_removal_result is changed

    - name: Remove {{ username }} home directory
      ansible.builtin.file:
        path: "/home/{{ username }}"
        state: absent

    - name: Exit session
      ansible.builtin.meta: reset_connection