name: Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Hello, Workflow on push!"
