name: Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  Running Script On Runner:
    runs-on: self-hosted
    steps:
      - name: Run check
        uses: actions/checkout@v4

      - name: Run a script
        run: sh hello.sh

      - name: Make folder
        run: mkdir hello

      - name: Push hello folder to github 
        run: git add . && git commit "Add Hello Folder" && git push
