name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
      uses: actions/checkout@v3

      - name: Install node.js
      uses: action/setup-node@v3
      with:
        node-version: '18'

      -name: install
      run: npm install 

      -name: run test
      run: npm test
